---
title: "discrete-truncated-student-t.Rmd"
author: "mjskay"
date: "August 19, 2016"
output: html_document
---

Test for discrete student t in rethinking

```{r}
library(rstan)
library(rethinking)
import::from(gamlss.dist, TF, rTF, qTF, pTF)
import::from(gamlss.tr, trun.r)
```

```{r stan}
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

```{r}
rethinking_env = loadNamespace("rethinking")
unlockBinding("map2stan.templates", rethinking_env)
rethinking_env$map2stan.templates$DiscreteTruncatedStudentT = 
    list(
        # not built into Stan, but can build from log_prob calculations
        # need to flag by using 'increment_log_prob' as distribution name
        # then provide separate model{} and gq{} code segments
        name = "DiscreteTruncatedStudentT",
        R_name = "ddtstudent",
        stan_name = "increment_log_prob",
        stan_code = "target += 
            //interval censoring: responses were rounded to intervals of size PAR4
            log_diff_exp(
                student_t_lcdf(OUTCOME + PAR4/2.0  | PAR1, PAR2, PAR3),
                student_t_lcdf(OUTCOME - PAR4/2.0  | PAR1, PAR2, PAR3)
            ) - 
            //truncation: only responses between PAR5 and PAR6 were allowed
            log_diff_exp(
                student_t_lcdf(PAR6 + PAR4/2.0  | PAR1, PAR2, PAR3),
                student_t_lcdf(PAR5 - PAR4/2.0  | PAR1, PAR2, PAR3)
            );",
        stan_dev = "dev = dev + (-2)*(
            //interval censoring: responses were rounded to intervals of size PAR4
            log_diff_exp(
                student_t_lcdf(OUTCOME + PAR4/2.0  | PAR1, PAR2, PAR3),
                student_t_lcdf(OUTCOME - PAR4/2.0  | PAR1, PAR2, PAR3)
            ) - 
            //truncation: only responses between PAR5 and PAR6 were allowed
            log_diff_exp(
                student_t_lcdf(PAR6 + PAR4/2.0  | PAR1, PAR2, PAR3),
                student_t_lcdf(PAR5 - PAR4/2.0  | PAR1, PAR2, PAR3)
            ));",
        num_pars = 6,
        par_names = c("nu","mu","sigma","width","lower","upper"),
        par_bounds = c("<lower=3>","","<lower=0>","<lower=0>","",""),
        par_types = c("real","real","real","real","real","real"),
        out_type = "real",
        par_map = function(k,e,...) {
            # get constraints and add <lower=0> for width, sigma, and nu
            constr_list <- get( "constraints" , envir=e )
            width_name <- as.character( k[[4]] )
            if ( is.null(constr_list[[width_name]]) ) {
                constr_list[[width_name]] <- "lower=0"
                assign( "constraints" , constr_list , envir=e )
            }
            nu_name <- as.character( k[[1]] )
            if ( is.null(constr_list[[nu_name]]) ) {
                constr_list[[nu_name]] <- "lower=3"
                assign( "constraints" , constr_list , envir=e )
            }
            sigma_name <- as.character( k[[3]] )
            if ( is.null(constr_list[[sigma_name]]) ) {
                constr_list[[sigma_name]] <- "lower=0"
                assign( "constraints" , constr_list , envir=e )
            }
            return(k);
        },
        vectorized = FALSE
    )
```

```{r}
ddtstudent = function(x, nu, mu, sigma, width = 1, lower = 0, upper = 100, log = FALSE) {
    stopifnot(all(lower <= upper))
    
    tolerance = sqrt(.Machine$double.eps)
    `width/2` = width/2
    p = ifelse(
        lower <= x & x <= upper & abs(x - round(x / width) * width) < tolerance, 
        (pTF(x + `width/2`, mu, sigma, nu) - pTF(x - `width/2`, mu, sigma, nu)) / 
            (pTF(upper + `width/2`, mu, sigma, nu) - pTF(lower - `width/2`, mu, sigma, nu)),
        0)
    
    if (log) log(p) else p
}

pdtstudent = function(q, nu, mu, sigma, width = 1, lower = 0, upper = 100, log.p = FALSE, lower.tail = TRUE) {
    stopifnot(all(lower <= upper))

    q = floor(q / width) * width
    `width/2` = width/2
    p = (pTF(q, mu, sigma, nu) - (pTF(lower - `width/2`, mu, sigma, nu))) /
        (pTF(upper + `width/2`, mu, sigma, nu) - pTF(lower - `width/2`, mu, sigma, nu))

    if (!lower.tail) p = 1 - p 
    if (log.p) log(p) else p
}

qdtstudent = function(p, nu, mu, sigma, width = 1, lower = 0, upper = 100, log.p = FALSE, lower.tail = TRUE) {
    data.frame(p, nu, mu, sigma, width, lower, upper) %$% {
        stopifnot(all(lower <= upper))
        
        qt = trun.q(cbind(lower - width/2, upper + width/2), family = "TF", type="both", varying=TRUE)
        x = qt(p, mu = mu, sigma = sigma, nu = nu, log.p = log.p, lower.tail = lower.tail)
        round(x / width) * width
    }
}

rdtstudent = function(n, nu, mu, sigma, width = 1, lower = 0, upper = 100) {
    data.frame(1:n, nu, mu, sigma, width, lower, upper) %$% {
        stopifnot(all(lower <= upper))
        
        rt = trun.r(cbind(lower - width/2, upper + width/2), family = "TF", type="both", varying=TRUE)
        round(rt(n, mu, sigma, nu) / width) * width
    }
}
```

```{r}
d = data.frame(
    x = rdtstudent(100, 10, 50, 10)
)
```

```{r}
m.m2s = map2stan(alist(
        response ~ ddtstudent(nu, mu, sigma, 1, 1, 99),
    
        nu ~ dexp(0.03333333333333),
    
        mu <- mu_intercept + mu_b_p * (p - 50) + 50,
        mu_intercept ~ dnorm(0, 2.5),
        mu_b_p ~ dnorm(1, 0.5),
    
        log(sigma) <- sigma_intercept + sigma_v_intercept[participant],
        sigma_intercept ~ dnorm(-1, 1),
        sigma_v_intercept[participant] ~ dnorm(0, sigma_participant),
        sigma_participant ~ dnorm(0, 1.15)
    ),
    data = d,
    sample=FALSE
)
```
